version: "3.3"
services:
  tasmota-device-manager:
    build: .
#    context: .
#    environment:
#      CHOKIDAR_USERPOLLING: 'true'
    volumes:
      - /pub/appdata/docker/tdmgr/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    dns: 192.168.0.5
    ports:
      - "5810:5800"
      - "5910:5900"
    container_name: tasmota-device-manager
    hostname: tdmgr
    restart: unless-stopped
    network_mode: "bridge"
